Application:
    license_key: 242ace622b5c70e89266fd01d7df533e5284a13f
    poll_interval: 60
    newrelic_api_timeout: 10

    test:
      name: local

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -25s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic-plugin-agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic-plugin-agent:
      level: DEBUG
      propagate: True
      handlers: [console, file]
    requests:
      level: DEBUG
      propagate: True
      handlers: [console, file]
